#:schema ../node_modules/wrangler/config-schema.json

name = "hascii"
compatibility_date = "2024-05-02"
main = "index.ts"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./build/client", binding = "ASSETS" }

[observability]
enabled = true
